sudo: false
language: python
install:
  - pip install tox-travis
services:
  - mysql
  - postgresql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS quma_test_db;'
  - mysql -e "CREATE USER quma_test_user@localhost IDENTIFIED BY 'quma_test_password';"
  - mysql -e "GRANT ALL PRIVILEGES ON quma_test_db.* TO 'quma_test_user'@'localhost';"
  - psql -c "CREATE USER quma_test_user WITH PASSWORD 'quma_test_password';" -U postgres
  - psql -c 'ALTER USER quma_test_user WITH SUPERUSER;' -U postgres
  - psql -c 'CREATE DATABASE quma_test_db;' -U postgres
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3.5"
  - "pypy3.6"

script: tox
