name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: quma_test_user
          MYSQL_PASSWORD: quma_test_password
          MYSQL_DATABASE: quma_test_db
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    strategy:
      max-parallel: 1
      matrix:
        include:
          - python: '3.8'
            tox: py38
          - python: '3.9'
            tox: py39
          - python: '3.10'
            tox: py310
          - python: '3.11'
            tox: py311
          - python: '3.12'
            tox: py312
          - python: 'pypy3.9'
            tox: pypy39
          - python: 'pypy3.10'
            tox: pypy310
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: pyproject.toml
      - run: pip install tox
      - name: Run linter and tests
        run: tox run -e ${{ matrix.tox }}
